version: '3.8'

services:
    webserver:
        build: ./backend/.docker/nginx
        image: nginx:1.21.6-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - ./backend:/var/www/html
            - ./backend/.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
    backend:
        build:
            context: ./backend/.docker/php
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            - ./backend:/var/www/html
            - ./backend/.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www/html
    mongo:
        image: mongo:latest
        container_name: mongodb
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: p455w0rd
        volumes:
            - ./mongo:/mongo/db
